[package]
name = "kanash-ratzilla"
version = "0.1.0"
authors = ["Benoit Leroux <benoitleroux41@gmail.com>"]
edition = "2021"
description = "Learn Hiragana and Katakana in a terminal !"
repository = "https://github.com/benoitlx/kanash"
license = "MIT"
keywords = ["ratatui", "learning", "japanese", "TUI"]

[dependencies]
kanash-components = { path = "../kanash-components/" }
ratzilla = "0.2.0"
web-time = "1.1.0"

[dev-dependencies]
web-sys = "0.3.82"
